---
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    command: minio server /data
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key

  local:
    build: local
    depends_on:
      - minio
    command: /src/local/idle.sh
    volumes:
      - .:/src
      - local-data:/persistent

volumes:
  minio-data: {}
  local-data: {}
